import { ArrowRight, BadgeCheck, Bike, HeartHandshake, Home, MapPin, Search, ShieldCheck, Sparkles, Store, UsersRound, UtensilsCrossed, Wrench } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { CatalogCard, ResponsiveImage, SkeletonCard } from '../../features/catalog/components/CatalogCards';
import { districts } from '../../features/catalog/data/mockCatalogData';
import { useCatalog } from '../../features/catalog/hooks/useCatalog';
import { useFavorites } from '../../features/catalog/hooks/useFavorites';
import { filterCatalog } from '../../features/catalog/utils/filterCatalog';
import type { CatalogItem } from '../../types';
import { Button, buttonStyles } from '../../shared/components/Button';
import { Modal } from '../../shared/components/Modal';
import { PublicHeader, SiteFooter } from '../../shared/layout/PublicLayout';
import { RequestContactModal } from '../../features/catalog/components/RequestContactModal';
import { Toast } from '../../shared/components/Feedback';

const categoryCards = [
  { title: 'Homemade Food', copy: 'Fresh meals and products from local home-based sellers.', href: '/user?track=PRODUCTS', image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85', icon: UtensilsCrossed, tone: 'bg-primary-soft text-primary' },
  { title: 'Delivery', copy: 'Reliable neighborhood delivery for food, packages, and everyday needs.', href: '/user?category=service-delivery', image: 'https://images.unsplash.com/photo-1617347454431-f49d7ff5c3b1?auto=format&fit=crop&w=900&q=85', icon: Bike, tone: 'bg-blue-soft text-blue' },
  { title: 'Home Services', copy: 'Find trusted cleaning, maintenance, and transportation providers nearby.', href: '/user?track=SERVICES', image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=85', icon: Wrench, tone: 'bg-sage-soft text-success' },
];
const steps = [{ title: 'Find what you need', copy: 'Browse local products and services in your district.', icon: Search }, { title: 'Request and connect', copy: 'Send a request and communicate directly with the provider.', icon: HeartHandshake }, { title: 'Receive local support', copy: 'Complete your order while supporting people in your community.', icon: Home }];
const trust = [{ title: 'Verified Providers', copy: 'Approved profiles you can recognize.', icon: BadgeCheck }, { title: 'Local and Nearby', copy: 'Made and offered around your neighborhood.', icon: UsersRound }, { title: 'Safe and Transparent', copy: 'Clear provider and listing information.', icon: ShieldCheck }, { title: 'Stronger Istanbul Neighborhoods', copy: 'Every request supports someone local.', icon: Store }];

export function LandingPage() {
  const navigate = useNavigate(); const catalog = useCatalog(); const favorites = useFavorites(); const [district, setDistrict] = useState(''); const [search, setSearch] = useState(''); const [help, setHelp] = useState(false); const [request, setRequest] = useState<CatalogItem | null>(null); const [toast, setToast] = useState<string | null>(null);
  const valid = filterCatalog({ providers: catalog.providers, products: catalog.products, services: catalog.services, productCategories: catalog.productCategories, serviceCategories: catalog.serviceCategories }, { district: '', search: '', track: 'ALL', categoryId: null });
  const featured = [...valid.filter((entry) => entry.kind === 'product').slice(0,3), ...valid.filter((entry) => entry.kind === 'service').slice(0,3)];
  const explore = (event?: React.FormEvent) => { event?.preventDefault(); const params = new URLSearchParams(); if (district) params.set('district', district); if (search.trim()) params.set('search', search.trim()); navigate(`/user${params.size ? `?${params}` : ''}`); };
  const card = (entry: CatalogItem) => { const id = `${entry.kind}:${entry.kind === 'product' ? entry.item.productId : entry.item.serviceId}`; return <CatalogCard key={id} entry={entry} favorite={favorites.isFavorite(id)} onFavorite={() => favorites.toggleFavorite(id)} onRequest={() => setRequest(entry)}/>; };
  return <div className="min-h-screen bg-page text-body"><PublicHeader onHelp={() => setHelp(true)}/><main>
    <section className="overflow-hidden border-b border-border bg-surface"><div className="mx-auto grid max-w-7xl gap-9 px-4 py-10 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-16"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Local people. Real support.</p><h1 className="mt-4 max-w-2xl text-4xl font-bold leading-[1.08] tracking-[-0.04em] text-heading sm:text-[52px]">Good Help, Close to Home</h1><p className="mt-5 max-w-xl text-lg leading-8 text-body">Discover trusted homemade food and everyday services from people in your neighborhood.</p><form onSubmit={explore} className="mt-8 grid gap-3 rounded-2xl border border-border bg-page p-3 shadow-card sm:grid-cols-[170px_1fr_auto]"><label><span className="sr-only">District</span><select aria-label="District" value={district} onChange={(event) => setDistrict(event.target.value)} className="h-14 w-full rounded-xl border border-border-strong bg-surface px-4 font-semibold text-heading outline-none focus:border-primary"><option value="">All Istanbul</option>{districts.map((item) => <option key={item.districtId}>{item.name}</option>)}</select></label><label className="relative"><span className="sr-only">What do you need?</span><Search className="absolute start-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="What do you need today?" className="h-14 w-full rounded-xl border border-border-strong bg-surface ps-12 pe-4 outline-none focus:border-primary"/></label><Button type="submit" className="!h-14">Search</Button></form><Link to="/user" className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary hover:text-primary-hover">Explore all of Jisr <ArrowRight className="h-4 w-4"/></Link></div><div className="relative aspect-[16/12] overflow-hidden rounded-2xl bg-primary-soft lg:aspect-[16/13]"><ResponsiveImage src="https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=88" alt="Local home cook preparing a fresh meal"/><div className="absolute bottom-4 start-4 rounded-xl bg-surface/95 p-3 shadow-card"><p className="text-sm font-semibold text-heading">Made with care nearby</p><p className="mt-0.5 inline-flex items-center gap-1 text-xs text-muted"><MapPin className="h-3 w-3"/>Across Istanbul</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-20"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Explore locally</p><h2 className="mt-3 text-[28px] font-semibold tracking-tight text-heading sm:text-[32px]">Whatever your day needs</h2><p className="mt-2 text-muted">Food, errands, and everyday expertise from people around the corner.</p></div><div className="mt-8 grid gap-4 md:grid-cols-3 md:gap-5">{categoryCards.map(({ title, copy, href, image, icon: Icon, tone }) => <Link key={title} to={href} className="group overflow-hidden rounded-xl border border-border bg-surface shadow-card transition-colors hover:border-border-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"><div className="relative aspect-[16/9] overflow-hidden bg-page"><ResponsiveImage src={image} alt="" className="transition-transform duration-300 group-hover:scale-[1.025]"/><span className={`absolute bottom-3 start-3 flex h-11 w-11 items-center justify-center rounded-xl shadow-card ${tone}`}><Icon className="h-5 w-5"/></span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-semibold text-heading">{title}</h3><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-border text-primary transition-colors group-hover:border-primary group-hover:bg-primary group-hover:text-white"><ArrowRight className="h-4 w-4"/></span></div><p className="mt-2 text-sm leading-6 text-muted">{copy}</p></div></Link>)}</div></section>
    <section className="border-y border-border bg-surface"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-20"><div className="flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Popular near you</p><h2 className="mt-3 text-[28px] font-semibold text-heading">Fresh from the neighborhood</h2></div><Link to="/user" className="hidden min-h-11 items-center text-sm font-semibold text-primary sm:flex">View marketplace →</Link></div>{catalog.loading ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map((item) => <SkeletonCard key={item}/>)}</div> : <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featured.map(card)}</div>}</div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl scroll-mt-24 px-4 py-12 sm:px-6 lg:px-8 lg:py-20"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Simple and neighborly</p><h2 className="mt-3 text-[28px] font-semibold text-heading">How Jisr works</h2></div><div className="mt-10 grid gap-8 md:grid-cols-3">{steps.map(({ title, copy, icon: Icon }, index) => <article key={title} className="text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-primary-soft text-primary"><Icon className="h-6 w-6"/></span><p className="mt-5 text-xs font-bold uppercase tracking-widest text-primary">Step {index + 1}</p><h3 className="mt-2 text-lg font-semibold text-heading">{title}</h3><p className="mx-auto mt-2 max-w-xs text-sm leading-6 text-muted">{copy}</p></article>)}</div></section>
    <section className="border-y border-border bg-sage-soft/60"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-12 sm:grid-cols-2 sm:px-6 lg:grid-cols-4 lg:px-8 lg:py-16">{trust.map(({ title, copy, icon: Icon }) => <article key={title} className="flex gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-surface text-success"><Icon className="h-5 w-5"/></span><div><h3 className="font-semibold text-heading">{title}</h3><p className="mt-1 text-sm leading-5 text-muted">{copy}</p></div></article>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-20"><div className="overflow-hidden rounded-2xl bg-heading px-6 py-10 text-white sm:px-10 lg:flex lg:items-center lg:justify-between lg:p-14"><div><span className="inline-flex items-center gap-1 rounded-full bg-white/10 px-3 py-1 text-xs font-semibold"><Sparkles className="h-3.5 w-3.5"/>Grow close to home</span><h2 className="mt-4 text-3xl font-bold">Turn your skills into a local business</h2><p className="mt-3 max-w-2xl text-base leading-7 text-white/70">Join Jisr as a home-based seller or service provider and reach customers in your neighborhood.</p></div><Link to="/register?role=provider" className={buttonStyles('primary', 'mt-7 w-full !h-[52px] sm:w-auto lg:mt-0')}>Become a Provider</Link></div></section>
  </main><SiteFooter/><RequestContactModal entry={request} onClose={() => setRequest(null)} onSuccess={setToast}/><Modal open={help} onClose={() => setHelp(false)} title="How can we help?"><p className="text-sm leading-6 text-muted">Questions about finding a provider or joining Jisr? Our demo support team is here to guide you.</p><a className={buttonStyles('primary', 'mt-5 w-full')} href="mailto:hello@jisr.example">Email Jisr support</a></Modal><Toast message={toast} onClose={() => setToast(null)}/></div>;
}
