import { Eye, ImageIcon, Pencil, Power, Trash2 } from 'lucide-react';
import type { ProductItem, ServiceItem } from '../../../types';
import { Button } from '../../../shared/components/Button';
import { EmptyState } from '../../../shared/components/Feedback';
import { StatusBadge } from '../../../shared/components/StatusBadge';
import { formatCurrency, formatDate } from '../utils/dashboard';

type Listing = ProductItem | ServiceItem;
const listingId = (item: Listing) => 'productId' in item ? item.productId : item.serviceId;
export interface ListingTableProps { kind: 'product' | 'service'; items: Listing[]; categoryName: (id: string) => string; onEdit: (item: Listing) => void; onToggle: (item: Listing) => void; onDelete: (item: Listing) => void; onAdd: () => void; onViewRequests?: () => void }

function ListingImage({ item }: { item: Listing }) { return item.imageUrl ? <img src={item.imageUrl} alt={`${item.title} listing`} className="h-12 w-14 rounded-lg object-cover"/> : <span className="flex h-12 w-14 items-center justify-center rounded-lg bg-page text-muted"><ImageIcon className="h-5 w-5"/></span>; }
function Actions({ item, kind, onEdit, onToggle, onDelete, onViewRequests }: Omit<ListingTableProps, 'items' | 'categoryName' | 'onAdd'> & { item: Listing }) { return <div className="flex flex-wrap justify-end gap-1"><Button variant="ghost" className="!min-h-9 !px-2.5" icon={<Pencil className="h-4 w-4"/>} onClick={() => onEdit(item)} aria-label={`Edit ${item.title}`}>Edit</Button><Button variant="ghost" className="!min-h-9 !px-2.5" icon={<Power className="h-4 w-4"/>} onClick={() => onToggle(item)}>{item.isAvailable ? 'Pause' : 'Enable'}</Button>{kind === 'service' && <Button variant="ghost" className="!min-h-9 !px-2.5" icon={<Eye className="h-4 w-4"/>} onClick={onViewRequests}>Requests</Button>}<Button variant="ghost" className="!min-h-9 !px-2.5 !text-danger" icon={<Trash2 className="h-4 w-4"/>} onClick={() => onDelete(item)} aria-label={`Delete ${item.title}`}>Delete</Button></div>; }

export function ListingTable(props: ListingTableProps) {
  const { items, kind, categoryName, onAdd } = props;
  if (!items.length) return <EmptyState title={kind === 'product' ? 'No products yet' : 'No services yet'} description={kind === 'product' ? 'Add your first product so customers can discover your business.' : 'Add your first service so nearby customers can request it.'} action={<Button onClick={onAdd}>{kind === 'product' ? 'Add your first product' : 'Add your first service'}</Button>}/>;
  return <>
    <div className="hidden overflow-hidden rounded-xl border border-border md:block" data-testid="desktop-listing-table"><table className="w-full border-collapse text-left text-sm"><thead className="h-12 bg-page text-xs font-semibold uppercase tracking-wide text-muted"><tr><th className="px-4">Listing</th><th className="px-4">Category</th><th className="px-4">Price</th><th className="px-4">Status</th><th className="px-4">Created</th><th className="px-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border">{items.map((item) => <tr key={listingId(item)} className="min-h-16 hover:bg-page/70"><td className="px-4 py-3"><div className="flex items-center gap-3"><ListingImage item={item}/><div><p className="font-semibold text-heading">{item.title}</p><p className="max-w-[200px] truncate text-xs text-muted">{item.description || 'No description'}</p></div></div></td><td className="px-4 py-3 text-body">{categoryName('productCategoryId' in item ? item.productCategoryId : item.serviceCategoryId)}</td><td className="whitespace-nowrap px-4 py-3 font-semibold text-heading">{formatCurrency(item.price)}</td><td className="px-4 py-3"><StatusBadge status={item.isAvailable ? 'AVAILABLE' : 'UNAVAILABLE'}/></td><td className="whitespace-nowrap px-4 py-3 text-muted">{formatDate(item.createdAt)}</td><td className="px-4 py-3"><Actions item={item} {...props}/></td></tr>)}</tbody></table></div>
    <div className="grid gap-3 md:hidden" data-testid="mobile-listing-cards">{items.map((item) => <article key={listingId(item)} className="rounded-xl border border-border bg-surface p-4"><div className="flex gap-3"><ListingImage item={item}/><div className="min-w-0 flex-1"><p className="truncate font-semibold text-heading">{item.title}</p><p className="text-sm text-muted">{categoryName('productCategoryId' in item ? item.productCategoryId : item.serviceCategoryId)}</p><p className="mt-1 font-semibold text-heading">{formatCurrency(item.price)}</p></div><StatusBadge status={item.isAvailable ? 'AVAILABLE' : 'UNAVAILABLE'}/></div><div className="mt-4 border-t border-border pt-2"><Actions item={item} {...props}/></div></article>)}</div>
  </>;
}
