import { ClipboardList, LayoutDashboard, LogOut, MessageCircle, Package, Settings, Store, UserRound, X } from 'lucide-react';
import type { Provider } from '../../../types';

export type NavAction = 'overview' | 'listings' | 'orders' | 'messages' | 'availability' | 'profile' | 'settings' | 'logout';
export interface ProviderSidebarProps { provider: Provider; mobile?: boolean; open?: boolean; onClose?: () => void; onAction: (action: NavAction) => void }
export function Brand() { return <div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-sage-soft text-success"><svg viewBox="0 0 32 32" className="h-6 w-6 fill-current" aria-hidden="true"><path d="M15.3 27.2c-1.4-7.7 1.2-14.4 8-20.2 1.4 7.4-1.1 14.2-8 20.2ZM13.5 24.1C7.1 21.7 4 16.6 4.2 8.7c6.8 2.8 9.9 7.9 9.3 15.4Z"/></svg></span><span className="text-xl font-bold tracking-tight text-heading">Jisr</span></div>; }
export function ProviderSidebar({ provider, mobile = false, open = true, onClose, onAction }: ProviderSidebarProps) {
  const itemLabel = provider.providerType === 'HOME_PRODUCT' ? 'Products' : 'Services';
  const items: { label: string; action: NavAction; icon: typeof LayoutDashboard }[] = [{ label: 'Overview', action: 'overview', icon: LayoutDashboard }, { label: itemLabel, action: 'listings', icon: Package }, { label: 'Orders', action: 'orders', icon: ClipboardList }, { label: 'Messages', action: 'messages', icon: MessageCircle }, { label: 'Availability', action: 'availability', icon: Store }, { label: 'Profile', action: 'profile', icon: UserRound }, { label: 'Settings', action: 'settings', icon: Settings }];
  const content = <aside className={`flex h-full w-60 flex-col border-r border-border bg-surface ${mobile ? 'shadow-xl' : ''}`}><div className="flex h-[72px] items-center justify-between border-b border-border px-6"><Brand/>{mobile && <button type="button" aria-label="Close navigation" onClick={onClose} className="flex h-11 w-11 items-center justify-center rounded-lg hover:bg-page"><X className="h-5 w-5"/></button>}</div><nav aria-label="Provider dashboard" className="flex-1 space-y-1 px-3 py-6">{items.map(({ label, action, icon: Icon }, index) => <button key={action} type="button" onClick={() => { onAction(action); onClose?.(); }} className={`flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm font-medium transition-colors ${index === 0 ? 'bg-primary-soft text-primary' : 'text-body hover:bg-page hover:text-heading'}`}><Icon className="h-[18px] w-[18px]"/>{label}</button>)}</nav><div className="border-t border-border p-3"><button type="button" onClick={() => onAction('logout')} className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm font-medium text-danger hover:bg-red-50"><LogOut className="h-[18px] w-[18px]"/>Log out</button><div className="mt-3 rounded-xl bg-page p-3"><p className="truncate text-sm font-semibold text-heading">{provider.businessName}</p><p className="mt-0.5 text-xs text-muted">{provider.district}, İstanbul</p></div></div></aside>;
  if (!mobile) return <div className="fixed inset-y-0 left-0 z-30 hidden lg:block">{content}</div>;
  if (!open) return null;
  return <div className="fixed inset-0 z-50 bg-heading/30 lg:hidden" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose?.(); }}>{content}</div>;
}
