import { MapPin, Pencil } from 'lucide-react';
import { useState } from 'react';
import type { Provider } from '../../../types';
import { Button } from '../../../shared/components/Button';
import { Input } from '../../../shared/components/FormControls';
import { StatusBadge } from '../../../shared/components/StatusBadge';
import { providerTypeLabel } from './ProviderHeader';

export interface ProviderProfileCardProps { provider: Provider; saving: boolean; onSave: (changes: Pick<Provider, 'businessName' | 'email' | 'phone' | 'district'>) => Promise<boolean>; onClose: () => void }
export function ProviderProfileCard({ provider, saving, onSave, onClose }: ProviderProfileCardProps) {
  const [editing, setEditing] = useState(false); const [values, setValues] = useState({ businessName: provider.businessName, email: provider.email, phone: provider.phone, district: provider.district }); const [submitted, setSubmitted] = useState(false);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); if (!values.businessName.trim() || !values.email.includes('@') || !values.phone.trim() || !values.district.trim()) return; if (await onSave({ ...values, businessName: values.businessName.trim(), phone: values.phone.trim(), district: values.district.trim() })) { setEditing(false); onClose(); } };
  if (editing) return <form noValidate onSubmit={save} className="space-y-5"><Input label="Business name" required value={values.businessName} onChange={(event) => setValues({ ...values, businessName: event.target.value })} error={submitted && !values.businessName.trim() ? 'Enter a business name.' : undefined}/><Input label="Email" required type="email" value={values.email} onChange={(event) => setValues({ ...values, email: event.target.value })} error={submitted && !values.email.includes('@') ? 'Enter a valid email.' : undefined}/><Input label="Phone" required value={values.phone} onChange={(event) => setValues({ ...values, phone: event.target.value })} error={submitted && !values.phone.trim() ? 'Enter a phone number.' : undefined}/><Input label="District" required value={values.district} onChange={(event) => setValues({ ...values, district: event.target.value })} error={submitted && !values.district.trim() ? 'Enter a district.' : undefined}/><div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={() => setEditing(false)}>Cancel</Button><Button type="submit" loading={saving}>Save profile</Button></div></form>;
  return <><div className="mb-6 flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-primary-soft text-lg font-bold text-primary">{provider.businessName.split(' ').slice(0,2).map((part) => part[0]).join('')}</span><div><h3 className="font-semibold text-heading">{provider.businessName}</h3><p className="text-sm text-muted">{providerTypeLabel(provider)}</p><div className="mt-2"><StatusBadge status={provider.status}/></div></div></div><dl className="space-y-4 rounded-xl bg-page p-4 text-sm"><div><dt className="text-muted">District</dt><dd className="mt-1 flex items-center gap-1.5 font-semibold text-heading"><MapPin className="h-4 w-4 text-primary"/>{provider.district}, İstanbul</dd></div><div><dt className="text-muted">Email</dt><dd className="mt-1 break-all font-semibold text-heading">{provider.email}</dd></div><div><dt className="text-muted">Phone</dt><dd className="mt-1 font-semibold text-heading">{provider.phone}</dd></div></dl><Button className="mt-6 w-full" variant="outline" icon={<Pencil className="h-4 w-4"/>} onClick={() => setEditing(true)}>Edit profile</Button></>;
}
