import { ArrowRight, HeartHandshake, Leaf, ShieldCheck, UsersRound } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { buttonStyles } from '../../shared/components/Button';
import { PublicHeader, SiteFooter } from '../../shared/layout/PublicLayout';

const pages: Record<string, { eyebrow: string; title: string; intro: string; sections: { title: string; copy: string }[] }> = {
  '/about': { eyebrow: 'About Jisr', title: 'A bridge between neighbors', intro: 'Jisr helps people discover homemade food and practical services offered by trusted people nearby.', sections: [{ title: 'Local by design', copy: 'District-aware discovery keeps the marketplace relevant to everyday life in Istanbul.' }, { title: 'Opportunity close to home', copy: 'Home sellers and independent providers can turn useful skills into sustainable local work.' }, { title: 'Simple connections', copy: 'Clear listings and direct requests make it easier for neighbors to help one another.' }] },
  '/careers': { eyebrow: 'Careers', title: 'Build better neighborhoods with us', intro: 'We are imagining a marketplace where technology strengthens local relationships and opportunity.', sections: [{ title: 'Product & design', copy: 'Shape calm, accessible tools for customers and local providers.' }, { title: 'Engineering', copy: 'Build reliable systems that respect people, privacy, and local context.' }, { title: 'Community operations', copy: 'Help providers succeed and customers feel supported.' }] },
  '/trust': { eyebrow: 'Trust & Safety', title: 'Trust grows through clarity', intro: 'Jisr is designed to make provider status, availability, prices, and request expectations easy to understand.', sections: [{ title: 'Provider review', copy: 'Approved badges are shown only for provider profiles reviewed by the platform.' }, { title: 'Transparent requests', copy: 'Customers see when an interaction is a demo and when a backend action has not occurred.' }, { title: 'Your control', copy: 'Favorites and demo requests stay on your device until secure accounts are connected.' }] },
  '/terms': { eyebrow: 'Terms', title: 'Straightforward platform terms', intro: 'This frontend is currently a demonstration and does not create binding orders, payments, or service agreements.', sections: [{ title: 'Demo interactions', copy: 'Requests, accounts, messages, and settings are local previews only.' }, { title: 'Provider responsibility', copy: 'Future providers will be responsible for accurate listings and fulfillment details.' }, { title: 'Customer responsibility', copy: 'Future customers will confirm requirements and final pricing before fulfillment.' }] },
  '/privacy': { eyebrow: 'Privacy', title: 'Designed with privacy in mind', intro: 'The current Jisr demo uses no backend account database and does not transmit form details to Jisr servers.', sections: [{ title: 'Local storage', copy: 'Favorites, preferences, and demo requests may be saved in your browser.' }, { title: 'No payment data', copy: 'This demo does not request, collect, or process payment information.' }, { title: 'Future controls', copy: 'Backend integration should add consent, deletion, and account-data controls.' }] },
};
export function InfoPage() { const { pathname } = useLocation(); const page = pages[pathname] ?? pages['/about']; return <div className="min-h-screen bg-page"><PublicHeader onHelp={() => document.getElementById('help')?.scrollIntoView({ behavior: 'smooth' })}/><main><section className="border-b border-border bg-surface"><div className="mx-auto max-w-4xl px-4 py-14 sm:px-6 lg:py-20"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{page.eyebrow}</p><h1 className="mt-4 text-4xl font-bold tracking-tight text-heading sm:text-5xl">{page.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-muted">{page.intro}</p></div></section><section className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:py-20"><div className="grid gap-5 md:grid-cols-3">{page.sections.map(({ title, copy }, index) => { const Icon = [UsersRound, HeartHandshake, ShieldCheck][index] ?? Leaf; return <article key={title} className="rounded-xl border border-border bg-surface p-6 shadow-card"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-sage-soft text-success"><Icon className="h-5 w-5"/></span><h2 className="mt-5 text-lg font-semibold text-heading">{title}</h2><p className="mt-2 text-sm leading-6 text-muted">{copy}</p></article>; })}</div><div className="mt-10 rounded-2xl bg-heading p-7 text-white sm:flex sm:items-center sm:justify-between"><div><h2 className="text-2xl font-semibold">See what’s available near you</h2><p className="mt-2 text-sm text-white/70">Explore local food and services across Istanbul.</p></div><Link to="/user" className={buttonStyles('primary', 'mt-5 w-full sm:mt-0 sm:w-auto')}>Explore Jisr<ArrowRight className="h-4 w-4"/></Link></div></section></main><SiteFooter/></div>; }
