import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes, useLocation } from 'react-router-dom';
import { beforeEach, describe, expect, it } from 'vitest';
import { catalogProviders, catalogProducts } from '../features/catalog/data/mockCatalogData';
import { LandingPage } from './landing/LandingPage';
import { UserCatalog } from './user/UserCatalog';
import { ResponsiveImage } from '../features/catalog/components/CatalogCards';
import { RequestContactModal } from '../features/catalog/components/RequestContactModal';
import { AuthPage } from './auth/AuthPage';
import { CustomerOrders } from './customer/CustomerOrders';
import { saveCustomerRequest } from '../features/catalog/data/customerRequests';

function LocationView() { const location = useLocation(); return <output aria-label="location">{location.pathname}{location.search}</output>; }
describe('customer experience', () => {
  beforeEach(() => { sessionStorage.clear(); });
  it('renders the landing page main sections', () => { render(<MemoryRouter><LandingPage/></MemoryRouter>); expect(screen.getByRole('heading', { name: 'Good Help, Close to Home' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Whatever your day needs' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'How Jisr works' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Turn your skills into a local business' })).toBeInTheDocument(); });
  it('navigates search and district to the customer URL', async () => { render(<MemoryRouter initialEntries={['/']}><Routes><Route path="/" element={<LandingPage/>}/><Route path="/user" element={<LocationView/>}/></Routes></MemoryRouter>); await userEvent.selectOptions(screen.getByLabelText('District'), 'Kadıköy'); await userEvent.type(screen.getByLabelText('What do you need?'), 'cleaning'); await userEvent.click(screen.getByRole('button', { name: 'Search' })); expect(screen.getByLabelText('location')).toHaveTextContent('/user?district=Kad%C4%B1k%C3%B6y&search=cleaning'); });
  it('opens and closes mobile navigation', async () => { render(<MemoryRouter><LandingPage/></MemoryRouter>); await userEvent.click(screen.getByRole('button', { name: 'Open navigation' })); expect(screen.getByRole('button', { name: 'Close navigation' })).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Close navigation' })); expect(screen.queryByRole('button', { name: 'Close navigation' })).not.toBeInTheDocument(); });
  it('shows customer account controls on the home page when signed in', async () => { sessionStorage.setItem('jisr-demo-session', JSON.stringify({ role: 'customer', email: 'user@example.com' })); render(<MemoryRouter><LandingPage/></MemoryRouter>); await userEvent.click(screen.getByRole('button', { name: 'Open user menu' })); expect(screen.getByRole('button', { name: 'Log out' })).toBeInTheDocument(); });
  it('shows a page empty state for unmatched search', async () => { render(<MemoryRouter initialEntries={['/user?search=zzzz-no-match']}><UserCatalog/></MemoryRouter>); expect(await screen.findByText('No providers available here yet', {}, { timeout: 2000 })).toBeInTheDocument(); });
  it('filters with product track and category controls', async () => { render(<MemoryRouter initialEntries={['/user']}><UserCatalog/></MemoryRouter>); await screen.findByRole('heading', { name: 'Home-Cooked Meals' }, { timeout: 2000 }); await userEvent.click(screen.getByRole('button', { name: 'Home Products' })); expect(screen.queryByRole('heading', { name: 'Delivery' })).not.toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Desserts' })); expect(screen.getByRole('heading', { name: 'Desserts' })).toBeInTheDocument(); });
  it('opens a URL-backed favorites view', async () => { render(<MemoryRouter initialEntries={['/user?favorites=true']}><UserCatalog/></MemoryRouter>); await screen.findByRole('heading', { name: 'Explore Jisr' }, { timeout: 2000 }); expect(screen.getByRole('button', { name: 'Favorites' })).toHaveAttribute('aria-pressed', 'true'); });
  it('validates required request details', async () => { const entry = { kind: 'product' as const, item: catalogProducts[0], provider: catalogProviders[0] }; render(<RequestContactModal entry={entry} onClose={() => undefined} onSuccess={() => undefined}/>); await userEvent.click(screen.getByRole('button', { name: 'Send Request' })); expect(screen.getByText('Tell the provider what you need.')).toBeInTheDocument(); expect(screen.getByText('Choose a preferred date.')).toBeInTheDocument(); });
  it('renders a placeholder for missing images', () => { render(<ResponsiveImage alt="Spinach Börek"/>); expect(screen.getByRole('img', { name: 'Spinach Börek image unavailable' })).toBeInTheDocument(); });
  it('validates and completes the mock login flow', async () => { render(<MemoryRouter initialEntries={['/login']}><Routes><Route path="/login" element={<AuthPage/>}/><Route path="/user" element={<LocationView/>}/></Routes></MemoryRouter>); await userEvent.click(screen.getByRole('button', { name: 'Log in' })); expect(screen.getByText('Enter a valid email address.')).toBeInTheDocument(); await userEvent.type(screen.getByLabelText(/Email address/), 'user@example.com'); await userEvent.type(screen.getByLabelText(/Password/), 'secret1'); await userEvent.click(screen.getByRole('button', { name: 'Log in' })); expect(await screen.findByLabelText('location')).toHaveTextContent('/user'); });
  it('shows persisted requests and supports cancellation', async () => { localStorage.clear(); saveCustomerRequest({ kind: 'product', item: catalogProducts[0], provider: catalogProviders[0] }, 'Two portions please', '2026-10-10', '18:00'); render(<MemoryRouter><CustomerOrders/></MemoryRouter>); expect(screen.getByText('Chicken Kabsa')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Cancel' })); expect(screen.getByRole('heading', { name: 'Cancel this request?' })).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Cancel request' })); expect(screen.getByText('Cancelled')).toBeInTheDocument(); });
  it('logs the customer out from the account menu', async () => { sessionStorage.setItem('jisr-demo-session', JSON.stringify({ role: 'customer', email: 'user@example.com' })); render(<MemoryRouter initialEntries={['/user']}><Routes><Route path="/user" element={<UserCatalog/>}/><Route path="/login" element={<LocationView/>}/></Routes></MemoryRouter>); await screen.findByRole('heading', { name: 'Explore Jisr' }, { timeout: 2000 }); await userEvent.click(screen.getByRole('button', { name: 'Open user menu' })); await userEvent.click(screen.getByRole('button', { name: 'Log out' })); const dialog = screen.getByRole('dialog', { name: 'Log out of Jisr?' }); await userEvent.click(within(dialog).getByRole('button', { name: 'Log out' })); expect(screen.getByLabelText('location')).toHaveTextContent('/login'); });
});
