import type { Admin, Provider, Customer, Chat, Message } from '../types';

// ── Demo Admins ──────────────────────────────────────────────────
export const DEMO_ADMINS: Admin[] = [
  {
    adminId: 'super-001',
    fullName: 'Omar Al-Hassan',
    email: 'super@demo.com',
    role: 'SUPER_ADMIN',
    createdAt: '2025-01-01T09:00:00Z',
  },
  {
    adminId: 'support-001',
    fullName: 'Sara Al-Rashid',
    email: 'support@demo.com',
    role: 'SUPPORT_ADMIN',
    createdAt: '2025-02-15T09:00:00Z',
    createdByAdminId: 'super-001',
  },
  {
    adminId: 'support-002',
    fullName: 'Khaled Mansour',
    email: 'khaled@demo.com',
    role: 'SUPPORT_ADMIN',
    createdAt: '2025-03-10T09:00:00Z',
    createdByAdminId: 'super-001',
  },
];

// ── Demo Providers ───────────────────────────────────────────────
export const DEMO_PROVIDERS: Provider[] = [
  {
    providerId: 'p-001',
    fullName: 'Ahmad Saleh',
    businessName: 'Al Noor Kitchen',
    email: 'ahmad@alnoor.com',
    phone: '+966 50 123 4567',
    district: 'Al Olaya',
    providerType: 'HOME_PRODUCT',
    status: 'PENDING_APPROVAL',
    isOnline: false,
    createdAt: '2026-09-07T08:30:00Z',
  },
  {
    providerId: 'p-002',
    fullName: 'Fatima Al-Zahra',
    businessName: 'CleanPro Services',
    email: 'fatima@cleanpro.com',
    phone: '+966 55 987 6543',
    district: 'Al Malaz',
    providerType: 'GENERAL_SERVICE',
    status: 'PENDING_APPROVAL',
    isOnline: false,
    createdAt: '2026-09-07T10:15:00Z',
    description: 'Professional home cleaning and sanitization services for Riyadh neighborhoods.',
  },
  {
    providerId: 'p-003',
    fullName: 'Mohammed Al-Qasim',
    businessName: 'QuickFix Tech',
    email: 'mo@quickfix.com',
    phone: '+966 56 555 1234',
    district: 'Al Murabba',
    providerType: 'GENERAL_SERVICE',
    status: 'APPROVED',
    isOnline: true,
    createdAt: '2026-08-15T11:00:00Z',
    approvedByAdminId: 'super-001',
  },
  {
    providerId: 'p-004',
    fullName: 'Layla Hassan',
    businessName: 'Fresh Bites Catering',
    email: 'layla@freshbites.com',
    phone: '+966 50 444 7890',
    district: 'Al Nakheel',
    providerType: 'HOME_PRODUCT',
    status: 'APPROVED',
    isOnline: true,
    createdAt: '2026-08-20T14:30:00Z',
    approvedByAdminId: 'super-001',
  },
  {
    providerId: 'p-005',
    fullName: 'Saad Ibrahim',
    businessName: 'Saad Plumbing',
    email: 'saad@plumbing.com',
    phone: '+966 54 222 3456',
    district: 'Al Rawdah',
    providerType: 'GENERAL_SERVICE',
    status: 'BLOCKED',
    isOnline: false,
    createdAt: '2026-07-10T09:00:00Z',
  },
  {
    providerId: 'p-006',
    fullName: 'Noura Al-Ghamdi',
    businessName: 'Noura Home Goods',
    email: 'noura@homegoodss.com',
    phone: '+966 56 111 9999',
    district: 'Al Sulaimaniyah',
    providerType: 'HOME_PRODUCT',
    status: 'PENDING_APPROVAL',
    isOnline: false,
    createdAt: '2026-09-08T07:45:00Z',
    description: 'Handmade traditional household items and artisanal products.',
  },
];

// ── Demo Customers ───────────────────────────────────────────────
export const DEMO_CUSTOMERS: Customer[] = [
  {
    customerId: 'c-001',
    fullName: 'Ahmed Al-Mutairi',
    email: 'ahmed@gmail.com',
    phone: '+966 50 100 2000',
    district: 'Al Olaya',
    status: 'ACTIVE',
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    customerId: 'c-002',
    fullName: 'Mona Al-Subaie',
    email: 'mona@gmail.com',
    phone: '+966 55 300 4000',
    district: 'Al Malaz',
    status: 'ACTIVE',
    createdAt: '2026-07-12T10:00:00Z',
  },
  {
    customerId: 'c-003',
    fullName: 'Turki Al-Shehri',
    email: 'turki@hotmail.com',
    phone: '+966 56 500 6000',
    district: 'Al Nakheel',
    status: 'BLOCKED',
    createdAt: '2026-05-20T12:00:00Z',
  },
  {
    customerId: 'c-004',
    fullName: 'Reem Al-Dosari',
    email: 'reem@email.com',
    phone: '+966 50 700 8000',
    district: 'Al Murabba',
    status: 'ACTIVE',
    createdAt: '2026-08-05T09:30:00Z',
  },
  {
    customerId: 'c-005',
    fullName: 'Faisal Al-Qahtani',
    email: 'faisal@work.com',
    phone: '+966 54 900 1000',
    district: 'Al Rawdah',
    status: 'ACTIVE',
    createdAt: '2026-09-01T11:00:00Z',
  },
];

// ── Demo Chats ───────────────────────────────────────────────────
export const DEMO_CHATS: Chat[] = [
  {
    chatId: 'chat-001',
    customerId: 'c-001',
    providerId: 'p-003',
    customerName: 'Ahmed Al-Mutairi',
    providerName: 'Mohammed Al-Qasim',
    businessName: 'QuickFix Tech',
    assignedAdminId: 'support-001',
    assignedAdminName: 'Sara Al-Rashid',
    lastMessage: 'Can you confirm the appointment for tomorrow?',
    updatedAt: '2026-09-08T12:40:00Z',
    status: 'OPEN',
    unreadCount: 3,
  },
  {
    chatId: 'chat-002',
    customerId: 'c-002',
    providerId: 'p-004',
    customerName: 'Mona Al-Subaie',
    providerName: 'Layla Hassan',
    businessName: 'Fresh Bites Catering',
    assignedAdminId: null,
    lastMessage: 'I need help with my order',
    updatedAt: '2026-09-08T11:20:00Z',
    status: 'OPEN',
    unreadCount: 1,
  },
  {
    chatId: 'chat-003',
    customerId: 'c-004',
    providerId: 'p-003',
    customerName: 'Reem Al-Dosari',
    providerName: 'Mohammed Al-Qasim',
    businessName: 'QuickFix Tech',
    assignedAdminId: 'super-001',
    assignedAdminName: 'Omar Al-Hassan',
    lastMessage: 'Thank you for resolving this quickly!',
    updatedAt: '2026-09-08T09:00:00Z',
    status: 'OPEN',
    unreadCount: 0,
  },
  {
    chatId: 'chat-004',
    customerId: 'c-005',
    providerId: 'p-004',
    customerName: 'Faisal Al-Qahtani',
    providerName: 'Layla Hassan',
    businessName: 'Fresh Bites Catering',
    assignedAdminId: null,
    lastMessage: 'When will my delivery arrive?',
    updatedAt: '2026-09-07T18:00:00Z',
    status: 'CLOSED',
    unreadCount: 0,
  },
];

// ── Demo Messages ────────────────────────────────────────────────
export const DEMO_MESSAGES: Record<string, Message[]> = {
  'chat-001': [
    { messageId: 'm-001', chatId: 'chat-001', senderId: 'c-001', senderRole: 'CUSTOMER', senderName: 'Ahmed Al-Mutairi', text: 'Hi, I booked a repair service but never received confirmation.', createdAt: '2026-09-08T12:10:00Z' },
    { messageId: 'm-002', chatId: 'chat-001', senderId: 'p-003', senderRole: 'PROVIDER', senderName: 'QuickFix Tech', text: 'Hello Ahmed! Yes, your appointment is confirmed for September 9th at 10:00 AM.', createdAt: '2026-09-08T12:20:00Z' },
    { messageId: 'm-003', chatId: 'chat-001', senderId: 'support-001', senderRole: 'ADMIN', senderName: 'Sara Al-Rashid', text: "Hello Ahmed! I'm Sara from MahalleHub Support. I've reviewed your booking and everything looks good. Please let us know if you need anything else.", createdAt: '2026-09-08T12:30:00Z' },
    { messageId: 'm-004', chatId: 'chat-001', senderId: 'c-001', senderRole: 'CUSTOMER', senderName: 'Ahmed Al-Mutairi', text: 'Thank you Sara! Can you confirm the appointment for tomorrow?', createdAt: '2026-09-08T12:40:00Z' },
  ],
  'chat-002': [
    { messageId: 'm-005', chatId: 'chat-002', senderId: 'c-002', senderRole: 'CUSTOMER', senderName: 'Mona Al-Subaie', text: 'I need help with my order #4521. The items delivered were wrong.', createdAt: '2026-09-08T11:00:00Z' },
    { messageId: 'm-006', chatId: 'chat-002', senderId: 'p-004', senderRole: 'PROVIDER', senderName: 'Fresh Bites Catering', text: "I'm sorry to hear that! Please share a photo of what was delivered.", createdAt: '2026-09-08T11:15:00Z' },
    { messageId: 'm-007', chatId: 'chat-002', senderId: 'c-002', senderRole: 'CUSTOMER', senderName: 'Mona Al-Subaie', text: 'I need help with my order', createdAt: '2026-09-08T11:20:00Z' },
  ],
  'chat-003': [
    { messageId: 'm-008', chatId: 'chat-003', senderId: 'c-004', senderRole: 'CUSTOMER', senderName: 'Reem Al-Dosari', text: 'My technician never showed up for the 2PM slot today.', createdAt: '2026-09-08T08:30:00Z' },
    { messageId: 'm-009', chatId: 'chat-003', senderId: 'super-001', senderRole: 'ADMIN', senderName: 'Omar Al-Hassan', text: "Hello Reem, I'm Omar, the Super Admin. I've contacted the provider and they are on their way. ETA 30 minutes. Apologies for the inconvenience.", createdAt: '2026-09-08T08:45:00Z' },
    { messageId: 'm-010', chatId: 'chat-003', senderId: 'c-004', senderRole: 'CUSTOMER', senderName: 'Reem Al-Dosari', text: 'Thank you for resolving this quickly!', createdAt: '2026-09-08T09:00:00Z' },
  ],
  'chat-004': [
    { messageId: 'm-011', chatId: 'chat-004', senderId: 'c-005', senderRole: 'CUSTOMER', senderName: 'Faisal Al-Qahtani', text: 'When will my delivery arrive?', createdAt: '2026-09-07T18:00:00Z' },
  ],
};

// ── Demo stats ───────────────────────────────────────────────────
export const DEMO_STATS = {
  totalCustomers: DEMO_CUSTOMERS.length,
  totalProviders: DEMO_PROVIDERS.length,
  pendingApprovals: DEMO_PROVIDERS.filter(p => p.status === 'PENDING_APPROVAL').length,
  activeChats: DEMO_CHATS.filter(c => c.status === 'OPEN').length,
};
