import { Heart, Search, SlidersHorizontal, Sparkles, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import type { CatalogFilters, CatalogItem } from '../../types';
import { CatalogCard, SkeletonCard } from '../../features/catalog/components/CatalogCards';
import { RequestContactModal } from '../../features/catalog/components/RequestContactModal';
import { districts } from '../../features/catalog/data/mockCatalogData';
import { useCatalog } from '../../features/catalog/hooks/useCatalog';
import { useFavorites } from '../../features/catalog/hooks/useFavorites';
import { filterCatalog } from '../../features/catalog/utils/filterCatalog';
import { Button, buttonStyles } from '../../shared/components/Button';
import { EmptyState, Toast } from '../../shared/components/Feedback';
import { Modal } from '../../shared/components/Modal';
import { PublicHeader, SiteFooter } from '../../shared/layout/PublicLayout';

const trackValues = ['ALL', 'PRODUCTS', 'SERVICES'] as const;
export function UserCatalog() {
  const catalog = useCatalog(); const favorites = useFavorites(); const [params, setParams] = useSearchParams();
  const [request, setRequest] = useState<CatalogItem | null>(null); const [help, setHelp] = useState(false); const [mobileFilters, setMobileFilters] = useState(false); const [favoritesOnly, setFavoritesOnly] = useState(false); const [toast, setToast] = useState<string | null>(null);
  const trackParam = params.get('track'); const track: CatalogFilters['track'] = trackValues.includes(trackParam as CatalogFilters['track']) ? trackParam as CatalogFilters['track'] : 'ALL';
  const filters: CatalogFilters = { district: params.get('district') ?? '', search: params.get('search') ?? '', track, categoryId: params.get('category') };
  const update = (changes: Partial<CatalogFilters>) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => { if (value && value !== 'ALL') next.set(key === 'categoryId' ? 'category' : key, value); else next.delete(key === 'categoryId' ? 'category' : key); }); setParams(next, { replace: true }); };
  const source = { providers: catalog.providers, products: catalog.products, services: catalog.services, productCategories: catalog.productCategories, serviceCategories: catalog.serviceCategories };
  const visible = useMemo(() => filterCatalog(source, filters).filter((entry) => !favoritesOnly || favorites.isFavorite(`${entry.kind}:${entry.kind === 'product' ? entry.item.productId : entry.item.serviceId}`)), [catalog.providers, catalog.products, catalog.services, catalog.productCategories, catalog.serviceCategories, filters.district, filters.search, filters.track, filters.categoryId, favoritesOnly, favorites.favoriteIds]);
  const categories = [...(track !== 'SERVICES' ? catalog.productCategories.map((item) => ({ id: item.productCategoryId, name: item.name, kind: 'product' as const })) : []), ...(track !== 'PRODUCTS' ? catalog.serviceCategories.map((item) => ({ id: item.serviceCategoryId, name: item.name, kind: 'service' as const })) : [])].filter((category) => category && (category.kind === 'product' ? catalog.productCategories.find((item) => item.productCategoryId === category.id)?.isActive : catalog.serviceCategories.find((item) => item.serviceCategoryId === category.id)?.isActive));
  const categorySections = categories.map((category) => ({ ...category, items: visible.filter((entry) => entry.kind === category.kind && (entry.kind === 'product' ? entry.item.productCategoryId : entry.item.serviceCategoryId) === category.id) })).filter((section) => section.items.length);
  const clear = () => { setParams({}, { replace: true }); setFavoritesOnly(false); };
  const filterControls = <><label className="relative block flex-1"><span className="sr-only">Search marketplace</span><Search className="absolute start-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted"/><input value={filters.search} onChange={(event) => update({ search: event.target.value })} placeholder="Search food, services, or providers" className="h-14 w-full rounded-full border border-border-strong bg-surface ps-12 pe-4 outline-none focus:border-primary focus:ring-2 focus:ring-primary-soft"/></label><label><span className="sr-only">District</span><select aria-label="District" value={filters.district} onChange={(event) => update({ district: event.target.value })} className="h-14 w-full rounded-full border border-border-strong bg-surface px-5 font-medium text-heading outline-none focus:border-primary sm:w-48"><option value="">All districts</option>{districts.map((district) => <option key={district.districtId}>{district.name}</option>)}</select></label></>;
  const card = (entry: CatalogItem, compact = false) => { const id = `${entry.kind}:${entry.kind === 'product' ? entry.item.productId : entry.item.serviceId}`; return <CatalogCard key={id} entry={entry} compact={compact} favorite={favorites.isFavorite(id)} onFavorite={() => favorites.toggleFavorite(id)} onRequest={() => setRequest(entry)}/>; };
  return <div className="min-h-screen bg-page text-body"><PublicHeader mode="catalog" onHelp={() => setHelp(true)} onFavorites={() => setFavoritesOnly((value) => !value)}/><main><section className="border-b border-border bg-surface"><div className="mx-auto max-w-7xl px-4 py-9 sm:px-6 sm:py-12 lg:px-8"><span className="inline-flex items-center gap-1.5 rounded-full bg-primary-soft px-3 py-1 text-xs font-semibold text-primary"><Sparkles className="h-3.5 w-3.5"/>Made and offered nearby</span><h1 className="mt-4 text-[28px] font-bold tracking-tight text-heading sm:text-4xl">Explore Jisr</h1><p className="mt-2 text-base text-muted">Discover available food, delivery, cleaning, and everyday services near you.</p><div className="mt-6 hidden gap-3 sm:flex">{filterControls}</div><Button onClick={() => setMobileFilters(true)} variant="outline" className="mt-6 w-full sm:hidden" icon={<SlidersHorizontal className="h-4 w-4"/>}>Search & filters</Button></div></section>
      <div className="mx-auto max-w-7xl space-y-8 px-4 py-7 sm:px-6 sm:py-10 lg:px-8"><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-full border border-border bg-surface p-1">{trackValues.map((value) => <button key={value} aria-pressed={track === value} onClick={() => update({ track: value, categoryId: null })} className={`min-h-11 rounded-full px-4 text-sm font-semibold ${track === value ? 'bg-primary text-white' : 'text-body hover:bg-page'}`}>{value === 'ALL' ? 'All' : value === 'PRODUCTS' ? 'Home Products' : 'Local Services'}</button>)}</div><button aria-pressed={favoritesOnly} onClick={() => setFavoritesOnly((value) => !value)} className={`ms-auto inline-flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-semibold ${favoritesOnly ? 'border-primary bg-primary-soft text-primary' : 'border-border bg-surface text-body'}`}><Heart className={`h-4 w-4 ${favoritesOnly ? 'fill-current' : ''}`}/>Favorites</button></div><div className="flex gap-2 overflow-x-auto pb-1">{filters.categoryId && <button onClick={() => update({ categoryId: null })} className="flex min-h-11 shrink-0 items-center gap-1 rounded-full border border-primary bg-primary-soft px-4 text-sm font-semibold text-primary"><X className="h-4 w-4"/>Clear category</button>}{categories.map((category) => <button key={category.id} aria-pressed={filters.categoryId === category.id} onClick={() => update({ categoryId: filters.categoryId === category.id ? null : category.id })} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm font-semibold ${filters.categoryId === category.id ? 'border-primary bg-primary text-white' : 'border-border bg-surface hover:border-border-strong'}`}>{category.name}</button>)}</div>
        {catalog.loading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map((item) => <SkeletonCard key={item}/>)}</div> : catalog.error ? <div className="rounded-xl border border-border bg-surface p-8 text-center"><h2 className="text-xl font-semibold text-heading">We couldn’t load the marketplace</h2><p className="mt-2 text-sm text-muted">Something interrupted the local catalog. Please try again.</p><Button className="mt-5" onClick={catalog.retry}>Retry</Button></div> : !visible.length ? <div className="rounded-xl border border-border bg-surface"><EmptyState title={favoritesOnly ? 'You have not saved any favorites yet.' : 'No providers available here yet'} description={favoritesOnly ? 'Tap the heart on any listing to keep it here.' : 'Try another district, category, or search term.'} action={<Button onClick={clear}>Clear filters</Button>}/></div> : filters.categoryId ? <section><h2 className="mb-5 text-2xl font-semibold text-heading">{categories.find((category) => category.id === filters.categoryId)?.name}</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map((entry) => card(entry))}</div></section> : <div className="space-y-12">{categorySections.map((section) => <section key={section.id}><div className="mb-5 flex items-center justify-between"><h2 className="text-[22px] font-semibold text-heading sm:text-[28px]">{section.name}</h2><button onClick={() => update({ categoryId: section.id })} className="min-h-11 text-sm font-semibold text-primary hover:text-primary-hover">View All →</button></div><div className="flex gap-4 overflow-x-auto pb-2 sm:grid sm:grid-cols-2 sm:overflow-visible lg:grid-cols-4">{section.items.slice(0,4).map((entry) => card(entry, true))}</div></section>)}</div>}
      </div></main><SiteFooter/><RequestContactModal entry={request} onClose={() => setRequest(null)} onSuccess={setToast}/><Modal open={help} onClose={() => setHelp(false)} title="How can we help?"><p className="text-sm leading-6 text-muted">Jisr support is available for questions about local listings and demo requests.</p><a className={buttonStyles('primary', 'mt-5 w-full')} href="mailto:hello@jisr.example">Email Jisr support</a></Modal><Modal open={mobileFilters} onClose={() => setMobileFilters(false)} title="Search & filters"><div className="space-y-4">{filterControls}<Button className="w-full" onClick={() => setMobileFilters(false)}>Show results</Button></div></Modal><Toast message={toast} onClose={() => setToast(null)}/></div>;
}
