import { BadgeCheck, Heart, ImageIcon, MapPin } from 'lucide-react';
import { useState } from 'react';
import type { CatalogItem } from '../../../types';
import { Button } from '../../../shared/components/Button';
import { formatCurrency } from '../../provider/utils/dashboard';

export interface VerifiedBadgeProps { label?: string }
export function VerifiedBadge({ label = 'Verified' }: VerifiedBadgeProps) { return <span className="inline-flex items-center gap-1 text-xs font-semibold text-success"><BadgeCheck className="h-4 w-4"/>{label}</span>; }
export interface ResponsiveImageProps { src?: string | null; alt: string; className?: string }
export function ResponsiveImage({ src, alt, className = '' }: ResponsiveImageProps) { const [failed, setFailed] = useState(false); return src && !failed ? <img src={src} alt={alt} onError={() => setFailed(true)} className={`h-full w-full object-cover ${className}`}/> : <div role="img" aria-label={`${alt} image unavailable`} className={`flex h-full w-full items-center justify-center bg-primary-soft text-primary ${className}`}><ImageIcon className="h-9 w-9"/></div>; }
export interface FavoriteButtonProps { active: boolean; onClick: () => void; label: string }
export function FavoriteButton({ active, onClick, label }: FavoriteButtonProps) { return <button type="button" aria-label={`${active ? 'Remove' : 'Add'} ${label} ${active ? 'from' : 'to'} favorites`} aria-pressed={active} onClick={onClick} className={`absolute end-3 top-3 flex h-11 w-11 items-center justify-center rounded-full border shadow-sm transition ${active ? 'border-primary bg-primary text-white' : 'border-border bg-surface/95 text-body hover:text-primary'}`}><Heart className={`h-5 w-5 ${active ? 'fill-current' : ''}`}/></button>; }
export interface CatalogCardProps { entry: CatalogItem; favorite: boolean; onFavorite: () => void; onRequest: () => void; compact?: boolean }
export function CatalogCard({ entry, favorite, onFavorite, onRequest, compact = false }: CatalogCardProps) { const { item, provider } = entry; return <article className={`group flex h-full flex-col overflow-hidden rounded-xl border border-border bg-surface shadow-card ${compact ? 'min-w-[280px]' : ''}`}><div className="relative aspect-[4/3] overflow-hidden"><ResponsiveImage src={item.imageUrl} alt={item.title} className="transition-transform duration-300 group-hover:scale-[1.025]"/><FavoriteButton active={favorite} onClick={onFavorite} label={item.title}/><span className={`absolute bottom-3 start-3 rounded-full px-2.5 py-1 text-xs font-semibold ${entry.kind === 'product' ? 'bg-primary-soft text-primary' : 'bg-blue-soft text-blue'}`}>{entry.kind === 'product' ? 'Home product' : 'Local service'}</span></div><div className="flex flex-1 flex-col p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-semibold leading-6 text-heading">{item.title}</h3><p className="shrink-0 font-bold text-heading">{entry.kind === 'service' ? 'From ' : ''}{formatCurrency(item.price)}</p></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted">{item.description}</p><div className="mt-4 flex items-center justify-between gap-2 border-t border-border pt-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-heading">{provider.businessName}</p><div className="mt-1 flex items-center gap-2"><VerifiedBadge/><span className="inline-flex items-center gap-1 text-xs text-muted"><MapPin className="h-3.5 w-3.5"/>{provider.district}</span></div></div></div><Button onClick={onRequest} className="mt-4 w-full" variant="outline">Request & Contact</Button></div></article>; }
export function SkeletonCard() { return <div className="animate-pulse overflow-hidden rounded-xl border border-border bg-surface"><div className="aspect-[4/3] bg-border"/><div className="space-y-3 p-4"><div className="h-5 w-2/3 rounded bg-border"/><div className="h-4 rounded bg-border"/><div className="h-11 rounded-lg bg-border"/></div></div>; }
